"""Fine tuning relationships via joins table

Revision ID: 115d47a194a4
Revises: 06c10a3c157a
Create Date: 2024-03-21 16:18:50.328448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115d47a194a4'
down_revision = '06c10a3c157a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devs_companies',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('dev_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_devs_companies_company_id_companies')),
    sa.ForeignKeyConstraint(['dev_id'], ['devs.id'], name=op.f('fk_devs_companies_dev_id_devs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devs_companies')
    # ### end Alembic commands ###
